# Generated by Django 3.1.4 on 2021-01-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210113_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='good',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='author',
            name='authorDetail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='books.authordetail'),
        ),
    ]
