# Generated by Django 3.1.4 on 2021-01-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210108_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='hobby',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
